# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_941yf7p5zt/clone/recipe, last modified Thu May 29 08:40:52 2025
# ------------------------------------------------

package:
  name: httpcore
  version: 1.0.9
source:
  sha256: 6e34463af53fd2ab5d807f399a9b45ea31c3dfa2276f15a2c3f00afff6e176e8
  url: https://pypi.io/packages/source/h/httpcore/httpcore-1.0.9.tar.gz
build:
  number: '0'
  script: /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_941yf7p5zt/croot/httpcore_1748526061031/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: py313hca03da5_0
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.2.25 hca03da5_0
    - expat 2.7.1 h313beb8_0
    - hatch-fancy-pypi-readme 24.1.0 py313hca03da5_0
    - hatchling 1.27.0 py313hca03da5_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.16 h02f6b3c_0
    - packaging 24.2 py313hca03da5_0
    - pathspec 0.10.3 py313hca03da5_0
    - pip 25.1 pyhc872135_2
    - pluggy 1.5.0 py313hca03da5_0
    - python 3.13.2 h4862095_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h1a28f6b_0
    - setuptools 78.1.1 py313hca03da5_0
    - sqlite 3.45.3 h80987f9_0
    - tk 8.6.14 h6ba3021_0
    - trove-classifiers 2024.10.14 py313hca03da5_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - certifi
    - h11 >=0.16
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
  imports:
    - httpcore
  requires:
    - pip
about:
  description: The HTTP Core package provides a minimal low-level HTTP client, which
    does one thing only. Sending HTTP requests.
  dev_url: https://github.com/encode/httpcore
  doc_url: https://www.encode.io/httpcore/
  home: https://github.com/encode/httpcore
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: The next generation HTTP client.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 94e276b8-ee3b-4e18-adc8-340b8f433e92
  recipe-maintainers:
    - nicoddemus
    - synapticarbors
  remote_url: git@github.com:AnacondaRecipes/httpcore-feedstock.git
  sha: bf922a7a787fe76f6d2a10110d0d35537d06e5ca
