# This file created by conda-build 26.1.0
# ------------------------------------------------

package:
  name: libiconv
  version: '1.18'
source:
  - url: https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.18.tar.gz
    sha256: 3b08f5f4f9b4eb82f151a7040bfd6fe6c6fb922efe4b1659c66ea933276965e8
    patches:
      - patches/fix-aclocal-exact-tool-pin.patch
      - patches/utf_8_mac.patch
build:
  run_exports:
    - libiconv >=1.18,<2.0a0
  number: 0
  string: h92f5915_0
requirements:
  build:
    - clang_bootstrap_osx-arm64 20.1.8 h310783a_0
    - libltdl 2.6.0 haa24f5a_0
    - libtool 2.6.0 h50f4ffc_0
    - macosx_deployment_target_osx-arm64 12.1 h3601aa6_2
    - make 4.3 h620ffc9_1
  host:
    - __osx >=12.1
  run:
    - __osx >=12.1
test:
  requires:
    - jq
  commands:
    - iconv -l
    - test ! -f ${PREFIX}/bin/iconv
    - test_man_files=$(jq '.files[] | select( . | startswith("share/man"))' $CONDA_PREFIX/conda-meta/libiconv-1.18-${PKG_BUILD_STRING}.json)
    - if [[ ${test_man_files} ]]; then echo "found GPL licensed files being packaged
      ${test_man_files}"; exit 1; fi
    - test_doc_files=$(jq '.files[] | select( . | startswith("share/doc"))' $CONDA_PREFIX/conda-meta/libiconv-1.18-${PKG_BUILD_STRING}.json)
    - if [[ ${test_doc_files} ]]; then echo "found GPL licensed files being packaged
      ${test_doc_files}"; exit 1; fi
    - test -f $PREFIX/lib/libiconv${SHLIB_EXT}
    - test -f $PREFIX/lib/libcharset${SHLIB_EXT}
about:
  home: https://www.gnu.org/software/libiconv
  license: LGPL-2.1-only
  license_file: COPYING.LIB
  summary: Provides iconv for systems which don't have one (or that cannot convert
    from/to Unicode.)
extra:
  recipe-maintainers:
    - jakirkham
    - jhamman
    - mingwandroid
    - ocefpaf
    - scopatz
  final: true
  copy_test_source_files: true
  remote_url: https://github.com/AnacondaRecipes/libiconv-feedstock
  sha: a42f10c26cf243d7b6722426f4d1965fd7ad84e6
  task_id: Y4IJVstSTfubWVoAvm8ELw
  task_run_id: '0'
  pbp_graph_uuid: a645ec97-1204-48b8-b3a2-b8f08653019a
