export const workbookSheetNames = { data: "Data", groups: "Groups", variables: "Variables" } as const;
export const requiredDataColumns = ["Case"] as const;
export const groupsSheetColumns = ["GroupKey","DisplayName","Color","SortOrder","DefaultVisible"] as const;
export const variablesSheetColumns = ["VariableKey","DisplayName","GroupKey","Unit","DataType","SortOrder","DefaultVisible","Source"] as const;
export const allowedDataTypes = ["number","string","boolean","date"] as const;
export const allowedVariableSources = ["file","derived"] as const;
export const maxXlsxFileSizeBytes = 20 * 1024 * 1024;
export const maxRenderedTableRows = 5000;
export const maxPlotRows = 20000;
