# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /Users/ec2-user/tasks/task_176855925366147/python-dotenv-feedstock/recipe, last modified Fri Jan 16 10:34:28 2026
# ------------------------------------------------

package:
  name: python-dotenv
  version: 1.2.1
source:
  sha256: d9eebba53ff89f06bf99f2c87d2abef2b9da0790dc4b082ce1f9c5572f2cb1d0
  url: https://github.com/theskumar/python-dotenv/archive/refs/tags/v1.2.1.tar.gz
build:
  entry_points:
    - dotenv = dotenv.__main__:cli
  number: '0'
  script: /Users/ec2-user/croot/python-dotenv_1768559692832/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
    -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir
    -vv
  string: py313hca03da5_0
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2025.12.2 hca03da5_0
    - libcxx 20.1.8 hd7fd590_1
    - libexpat 2.7.3 h50f4ffc_4
    - libffi 3.4.4 hca03da5_1
    - libmpdec 4.0.0 h80987f9_0
    - libzlib 1.3.1 h5f15de7_0
    - ncurses 6.5 hee39554_0
    - openssl 3.0.18 h9b4081a_0
    - pip 25.3 pyhc872135_0
    - python 3.13.11 hc7d8306_100_cp313
    - python_abi 3.13 3_cp313
    - readline 8.3 h0b18652_0
    - setuptools 80.9.0 py313hca03da5_0
    - sqlite 3.51.1 hab6afd1_0
    - tk 8.6.15 hcd8a7d5_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313hca03da5_0
    - xz 5.6.4 h80987f9_1
    - zlib 1.3.1 h5f15de7_0
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
  run_constrained:
    - click >=5.0
test:
  commands:
    - pip check
    - pytest tests -vv -k "not (test_set_key_permission_error or test_set_key_unauthorized_file)"
  imports:
    - dotenv
  requires:
    - click
    - pip
    - pytest >=3.9
    - sh >=2
  source_files:
    - tests
about:
  description: 'Python-dotenv reads key-value pairs from a .env file and can set them
    as environment variables.

    It helps in the development of applications following the 12-factor principles.

    '
  dev_url: https://github.com/theskumar/python-dotenv
  doc_url: https://github.com/theskumar/python-dotenv/tree/main/docs
  home: https://saurabh-kumar.com/python-dotenv
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Get and set values in your .env file in local and production servers like
    Heroku does.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - proinsias
