import type { VariableDefinition } from "../types/appTypes";
export const defaultVariables: VariableDefinition[] = [
  { variableKey: "Case", displayName: "Case #", groupKey: "test_inputs", unit: "-", dataType: "number", sortOrder: 0, defaultVisible: true, source: "file" },
  { variableKey: "GrossWeight", displayName: "Gross Weight", groupKey: "test_inputs", unit: "lb", dataType: "number", sortOrder: 10, defaultVisible: true, source: "file" },
  { variableKey: "PressureAltitude", displayName: "Pressure Altitude", groupKey: "test_inputs", unit: "ft", dataType: "number", sortOrder: 20, defaultVisible: true, source: "file" },
  { variableKey: "OAT", displayName: "OAT", groupKey: "test_inputs", unit: "°C", dataType: "number", sortOrder: 30, defaultVisible: true, source: "file" },
  { variableKey: "VR_Exp", displayName: "VR Exp", groupKey: "expected_outputs", unit: "kt", dataType: "number", sortOrder: 10, defaultVisible: true, source: "file" },
  { variableKey: "V2_Exp", displayName: "V2 Exp", groupKey: "expected_outputs", unit: "kt", dataType: "number", sortOrder: 20, defaultVisible: true, source: "file" },
  { variableKey: "TODist_Exp", displayName: "TO Dist Exp", groupKey: "expected_outputs", unit: "m", dataType: "number", sortOrder: 30, defaultVisible: true, source: "file" },
  { variableKey: "VR_Act", displayName: "VR Act", groupKey: "actual_outputs", unit: "kt", dataType: "number", sortOrder: 10, defaultVisible: true, source: "file" },
  { variableKey: "V2_Act", displayName: "V2 Act", groupKey: "actual_outputs", unit: "kt", dataType: "number", sortOrder: 20, defaultVisible: true, source: "file" },
  { variableKey: "TODist_Act", displayName: "TO Dist Act", groupKey: "actual_outputs", unit: "m", dataType: "number", sortOrder: 30, defaultVisible: true, source: "file" },
  { variableKey: "VR_Tol", displayName: "VR Tol", groupKey: "tolerances", unit: "kt", dataType: "number", sortOrder: 10, defaultVisible: true, source: "derived" },
  { variableKey: "V2_Tol", displayName: "V2 Tol", groupKey: "tolerances", unit: "kt", dataType: "number", sortOrder: 20, defaultVisible: true, source: "derived" },
  { variableKey: "TODist_Tol", displayName: "TO Dist Tol", groupKey: "tolerances", unit: "m", dataType: "number", sortOrder: 30, defaultVisible: true, source: "derived" },
  { variableKey: "VR_AbsErr", displayName: "VR Abs Err", groupKey: "absolute_error", unit: "kt", dataType: "number", sortOrder: 10, defaultVisible: true, source: "derived" },
  { variableKey: "V2_AbsErr", displayName: "V2 Abs Err", groupKey: "absolute_error", unit: "kt", dataType: "number", sortOrder: 20, defaultVisible: true, source: "derived" },
  { variableKey: "TODist_AbsErr", displayName: "TO Dist Abs Err", groupKey: "absolute_error", unit: "m", dataType: "number", sortOrder: 30, defaultVisible: true, source: "derived" },
  { variableKey: "VR_RelErr", displayName: "VR Rel", groupKey: "relative_error", unit: "%", dataType: "number", sortOrder: 10, defaultVisible: true, source: "derived" },
  { variableKey: "V2_RelErr", displayName: "V2 Rel", groupKey: "relative_error", unit: "%", dataType: "number", sortOrder: 20, defaultVisible: true, source: "derived" },
  { variableKey: "TODist_RelErr", displayName: "TO Dist Rel", groupKey: "relative_error", unit: "%", dataType: "number", sortOrder: 30, defaultVisible: true, source: "derived" },
  { variableKey: "FlapsSetting", displayName: "Flaps Setting", groupKey: "inputs", unit: "-", dataType: "string", sortOrder: 10, defaultVisible: true, source: "file" },
  { variableKey: "RunwayCondition", displayName: "Runway Condition", groupKey: "inputs", unit: "-", dataType: "string", sortOrder: 20, defaultVisible: true, source: "file" },
  { variableKey: "AntiIce", displayName: "Anti-Ice", groupKey: "inputs", unit: "-", dataType: "string", sortOrder: 30, defaultVisible: true, source: "file" },
  { variableKey: "Notes", displayName: "Notes", groupKey: "logged_data", unit: "-", dataType: "string", sortOrder: 10, defaultVisible: true, source: "file" },
  { variableKey: "PassFail", displayName: "Pass/Fail", groupKey: "logged_data", unit: "-", dataType: "string", sortOrder: 20, defaultVisible: true, source: "file" },
];
