export const tooltipContent = {
  importXlsx: "Load an XLSX workbook. The workbook must contain a Data sheet with a Case column.",
  saveLayout: "Save the current group selection, visible variables, plot formatting, cursor options, and x-axis range.",
  export: "Export the visible table, plot image, or layout configuration.",
  settings: "Open app settings such as autosave layout and reset layout.",
  help: "Open help for workbook format, groups, plotting, cursors, and export.",
  dataGroups: "Show or hide complete configurable groups.",
  variablesSearch: "Filter variables by display name, variable key, unit, or group name.",
  selectAllVariables: "Show all variables in all visible groups.",
  clearAllVariables: "Hide all variables except Case #.",
  caseAlwaysVisible: "Case # is always visible because it is the required table key and plot x-axis.",
  xAxisNavigation: "Use these controls to zoom horizontally and focus on a specific case.",
  zoomMinus: "Zoom out horizontally around the selected case.",
  zoomPlus: "Zoom in horizontally around the selected case.",
  zoomSlider: "Adjust the horizontal case window from full range to a 10-case window.",
  overviewBrush: "Drag the handles to choose the visible case range.",
  focusCase: "Enter a case number and press Go to center the plots around that case.",
  previousCase: "Move the cursor to the previous available case.",
  nextCase: "Move the cursor to the next available case.",
  plotFormatting: "Configure visible plot series, line style, axes, grid, cursor, and zoom behavior.",
  seriesVisibility: "Show or hide this plotted series.",
  colorSwatch: "Choose the line color for this series.",
  lineStyle: "Choose solid, dashed, or dotted line style.",
  gridToggle: "Show or hide plot grid lines.",
  cursorToggle: "Show or hide the plot crosshair cursor.",
  snapToData: "Snap the cursor to the nearest available case.",
  showTooltips: "Show or hide floating plot value tooltips.",
} as const;
