#!/usr/bin/env python3
"""
CI version of daily_product_report.sh.
Uses the Anthropic SDK directly instead of the local Claude CLI.
Called by .github/workflows/daily-product-report.yml.
"""

import openai
import os
import subprocess
import sys
from datetime import date

TODAY = date.today().strftime("%Y-%m-%d")
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def read(path, default=""):
    try:
        with open(os.path.join(REPO, path)) as f:
            return f.read()
    except FileNotFoundError:
        return default


def main():
    git_log = subprocess.run(
        ["git", "log", "--oneline", "--since=24 hours ago"],
        capture_output=True, text=True, cwd=REPO,
    ).stdout.strip() or "(no commits today)"

    git_status = subprocess.run(
        ["git", "status", "--short"],
        capture_output=True, text=True, cwd=REPO,
    ).stdout.strip()[:2000] or "(clean)"

    charter = read("agents/game-director/charter.md")
    template = read("templates/daily-product-report.md")

    prompt = f"""You are the Game Director for Ashen Hollow, a metroidvania game in development.

## Your Charter
{charter}

## Report Template
{template}

## Today's Git Activity (last 24 hours)
Commits:
{git_log}

Uncommitted changes:
{git_status}

## Task
Today is {TODAY}. Write the daily product report for **Ashen Hollow**.

Fill in the template using the git activity above as evidence of accomplishments.
Focus on game design progress — charter updates, agent interactions, design decisions made,
creative problems resolved. If there is no direct game design activity in the git log,
report status honestly: "no game design commits today; toolchain work supports future production."
Mark any creative blockers, unresolved design questions, or decisions needing founder input.
Output clean markdown using the template structure. Do not add commentary outside the template."""

    client = openai.OpenAI()
    response = client.chat.completions.create(
        model="gpt-4o",
        max_tokens=4096,
        messages=[{"role": "user", "content": prompt}],
    )
    report = response.choices[0].message.content

    artifact = os.path.join(REPO, f"artifacts/daily-report-{TODAY}.md")
    os.makedirs(os.path.dirname(artifact), exist_ok=True)
    with open(artifact, "w") as f:
        f.write(
            f"# Daily Product Report — {TODAY}\n\n"
            f"---\n\n"
            f"{report}\n\n"
            f"---\n\n"
            f"*Generated by Agent OS daily product report. "
            f"Blockers and decisions are escalated immediately — they do not wait for Monday.*\n"
        )

    print(f"Saved to {artifact}", flush=True)

    subprocess.run(
        [
            sys.executable,
            os.path.join(REPO, "scripts/send_weekly_digest.py"),
            "--file", artifact,
            "--subject", f"[MV Toolchain] Daily Product Report — {TODAY}",
            "--subtitle", "Metroidvania Toolchain — Daily Product Report",
        ],
        check=True,
        cwd=REPO,
    )


if __name__ == "__main__":
    main()
