#!/bin/bash
# Daily Product Report — generates Workbench PO + Game Director reports via Claude CLI
# and emails them as a combined digest via Resend.
#
# Runs every weekday at 6:07pm via crontab.
# Install: crontab -e → add:
#   7 18 * * 1-5 /Users/timwood/Desktop/projects/PWA/MV/scripts/daily_product_report.sh

set -euo pipefail

REPO="/Users/timwood/Desktop/projects/PWA/MV"
CLAUDE="/opt/homebrew/bin/claude"
PYTHON="/usr/bin/python3"
LOG="$REPO/artifacts/daily-report-cron.log"

cd "$REPO"
source .env.local 2>/dev/null || true

TODAY=$(date +%Y-%m-%d)
ARTIFACT="$REPO/artifacts/daily-report-$TODAY.md"

echo "[$(date)] Starting daily product report" >> "$LOG"

# ── Build context ─────────────────────────────────────────────────────────────

GIT_LOG_TODAY=$(git log --oneline --since="24 hours ago" 2>/dev/null || echo "(no commits today)")
GIT_STATUS=$(git status --short 2>/dev/null | head -30 || echo "(clean)")

WB_CHARTER=$(cat "$REPO/agents/workbench-po/charter.md" 2>/dev/null)
GD_CHARTER=$(cat "$REPO/agents/game-director/charter.md" 2>/dev/null)
TEMPLATE=$(cat "$REPO/templates/daily-product-report.md" 2>/dev/null)

# ── Generate Workbench PO report ──────────────────────────────────────────────

echo "[$(date)] Generating Workbench report..." >> "$LOG"

WB_PROMPT=$(cat <<PROMPT
You are the Workbench Product Owner for the MV Sprite Workbench toolchain.

## Your Charter
$WB_CHARTER

## Report Template
$TEMPLATE

## Today's Git Activity (last 24 hours)
Commits:
$GIT_LOG_TODAY

Uncommitted changes:
$GIT_STATUS

## Task
Today is $TODAY. Write the daily product report for the **Sprite Workbench**.

Fill in the template using the git activity above as evidence of accomplishments.
Be specific: name actual files changed and what they represent as product progress.
If git activity is sparse, report honestly — "no code shipped; planning/design work in progress" is a valid accomplishment.
Mark any blockers, issues, or decisions needed with specific owners and resolution paths.
Output clean markdown using the template structure. Do not add commentary outside the template.
PROMPT
)

WB_REPORT=$("$CLAUDE" -p "$WB_PROMPT" --output-format text 2>>"$LOG")

if [ -z "$WB_REPORT" ]; then
  echo "[$(date)] ERROR: Empty Workbench report from Claude" >> "$LOG"
  exit 1
fi

# ── Generate Game Director report ─────────────────────────────────────────────

echo "[$(date)] Generating Ashen Hollow report..." >> "$LOG"

GD_PROMPT=$(cat <<PROMPT
You are the Game Director for Ashen Hollow, a metroidvania game in development.

## Your Charter
$GD_CHARTER

## Report Template
$TEMPLATE

## Today's Git Activity (last 24 hours)
Commits:
$GIT_LOG_TODAY

Uncommitted changes:
$GIT_STATUS

## Task
Today is $TODAY. Write the daily product report for **Ashen Hollow**.

Fill in the template using the git activity above as evidence of accomplishments.
Focus on game design progress — charter updates, agent interactions, design decisions made,
creative problems resolved. If there is no direct game design activity in the git log,
report status honestly: "no game design commits today; toolchain work supports future production."
Mark any creative blockers, unresolved design questions, or decisions needing founder input.
Output clean markdown using the template structure. Do not add commentary outside the template.
PROMPT
)

GD_REPORT=$("$CLAUDE" -p "$GD_PROMPT" --output-format text 2>>"$LOG")

if [ -z "$GD_REPORT" ]; then
  echo "[$(date)] ERROR: Empty Game Director report from Claude" >> "$LOG"
  exit 1
fi

# ── Combine into single artifact ──────────────────────────────────────────────

cat > "$ARTIFACT" <<EOF
# Daily Product Report — $TODAY

---

$WB_REPORT

---

$GD_REPORT

---

*Generated by Agent OS daily product report. Blockers and decisions are escalated immediately — they do not wait for Monday.*
EOF

echo "[$(date)] Saved to $ARTIFACT" >> "$LOG"

# ── Send email ────────────────────────────────────────────────────────────────

"$PYTHON" "$REPO/scripts/send_weekly_digest.py" \
  --file "$ARTIFACT" \
  --subject "[MV Toolchain] Daily Product Report — $TODAY" \
  --subtitle "Metroidvania Toolchain — Daily Product Report" \
  >> "$LOG" 2>&1

echo "[$(date)] Done" >> "$LOG"
